robot:
  name: "fr3"
  num_joints: 7
  gripper: true
  num_cameras: 2
fps: 15
start_episode: 0
end_episode: 10
hugging_face_repo: "SashoPepi"
dataset_name: "franka-gello-close-box_v8"
directory_path: "/workspace/ros2"
root_path: "/workspace/ros2"